### ISSUE TITLE
60fps gif plays back at slower speed

### ISSUE THREAD

**Issue by arechsteiner** [dudewheresmycode/GifTuna#7]
I have a 60fps video that I recorded with ShareX. I open it in Giftuna and the 60 FPS are correctly pre-set. However, when I export the file and open it in a browser, the gif plays back at a slower speed than the original.

I've attached both the .mp4 and the .gif.

[giftuna60fps.zip](https://github.com/dudewheresmycode/GifTuna/files/1441392/giftuna60fps.zip)

**Comment by dudewheresmycode** [comment]
I haven't played much with higher FPS gifs. But, it sounds an issue with translating the FPS to GIF delays. Gifs use a 1/100 second delay per frame, rather than a fixed frame rate. So to achieve 30FPS the GIF sets a frame delay of about 0.03 seconds (~30ms). The minimum delay for GIF format is a 0.02s delay, which makes the maximum achievable frame rate ~50fps.

An interesting article here about gif delays and playback limitations: http://nullsleep.tumblr.com/post/16524517190/animated-gif-minimum-frame-delay-browser

By inputing 60fps as your desired frame rate, ffmpeg is setting your delay to below 0.02s which 
most browsers / gif viewers will round back up to 0.10s (with all the frames that would normally be at 60fps), which is causing the gif to appear to playback very slow.

Should also note that many of the "60fps GIFS" you see are actually audio-less WEBM video files that were uploaded as video files at 60fps.
